drop table if exists user;

CREATE TABLE USER(
ID INT AUTO_INCREMENT PRIMARY KEY,
USERNAME VARCHAR(50) NOT NULL,
PASSWORD VARCHAR(100) NOT NULL
);

INSERT INTO USER (USERNAME,PASSWORD) VALUES ('Lorenzo','$2a$10$F9l18vKL0v5iTwOpBAApyO1RhiluMfBfZIaISz4ud.Kl9924X0fKe');
-- password 1234